### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by martoio** [kettensaur/My-Times#3]
Don't do this. Think about it. Does the text need to have an image? No, you want a box that has the image with text inside the box. => apply the background on the `.earth-image` directly and then you can center your text inside it.
https://github.com/kettensaur/My-Times/blob/a8c3c87a607aca052669034758fadbff0c7a6d98/resources/css/style.css#L80-L83

**Comment by martoio** [comment]
Full CSS below:
```css
.earth-image{
    background-image: url(https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-4/img-story-2.png);
    height: 300px;
    display: flex;
    justify-content: center;
    align-items: center;
}

.earth-image span{
    font-family: Georgia;
    font-weight: bold;
    font-size: 30px;
    color: white;
}
```
